### ISSUE TITLE
Add option to create_sysimage to include all packages in env

### ISSUE THREAD

**Issue by davidanthoff** [KristofferC/PackageCompilerX.jl#96]
Maybe if one just calls it without any package names (`create_sysimage()`) it could just add all the packages in the env to the sysimage?

Right now I manually do this in the VS Code extension [here](https://github.com/julia-vscode/julia-vscode/blob/593c11cf69698a13d1fa2f380abc0b3cb4ce52d4/scripts/tasks/task_compileenv.jl), but it seems this would have a better home in this package here itself.

**Comment by DilumAluthge** [comment]
Personally I think it’s better if you make the user manually spell out the packages they want to include in the sysimage. Otherwise, they may forget that they added the package `Foo` to their environment, and then `Foo` gets put in the sysimage, but they didn’t actually want `Foo` in the sysimage.

Making the user provide the package name or a list of package names makes sure that the sysimage only contains what they intend it to contain.

**Comment by davidanthoff** [comment]
This is for the VS Code use case, where there is a command that creates a separate sysimage for a given env, and in that scenario the simplest thing is to just include everything in that env (really think of it as a precompile for an env on steroids).

**Comment by KristofferC** [comment]
I like having to be explicit. If someone really wants it they can write one based on `Pkg.dependencies` or something.
